# Generated by Django 2.1.1 on 2018-09-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180917_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Description', to_field='desc'),
        ),
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
