# Generated by Django 2.1.1 on 2018-09-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180917_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_desc',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
