# Generated by Django 2.1.1 on 2018-09-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180917_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_desc',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='courses.Course'),
            preserve_default=False,
        ),
    ]
