# Generated by Django 2.1.1 on 2018-09-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180917_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Description', to_field='desc'),
        ),
    ]
